services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    working_dir: /app/apps/server
    command: bun dev

  www:
    build:
      context: .
      dockerfile: apps/www/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    working_dir: /app/apps/www
    command: bun dev
