services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    volumes:
      - .:/app
    working_dir: /app/apps/server
    depends_on:
      - rabbitmq
    entrypoint: ["/app/wait-for-rabbit.sh"]
    command: bun dev

  www:
    build:
      context: .
      dockerfile: apps/www/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    working_dir: /app/apps/www
    command: bun dev
